### ISSUE TITLE
Wrong package declaration in test cases

### ISSUE THREAD

**Issue by mipastgt** [geographiclib/geographiclib-java#1]
The test classes `GeodesicTest`  and `SignTest` have the wrong package declaration and thus these classes don't compile. Change the package declaration to `package net.sf.geographiclib;` to fix this. The import `import net.sf.geographiclib.*;` is then also not needed anymore.

**Comment by cffk** [comment]
Before I make these changes, can you

* tell me how to trigger the compilation error you get -- `mvn test` completes OK for me;
* point me to some documentation on the conventions for package names for tests.

Thanks.

**Comment by mipastgt** [comment]
In some cases this may work but it is generally considered bad practice and also IDEs stumble over this (like me).
Here is a link to an old bug report for Eclipse which may provide some details.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=16209
Fact is, you don't get this through Eclipse.

**Comment by mipastgt** [comment]
Thank you. :-)

**Comment by cffk** [comment]
You're welcome.  Java isn't my first language (nor my second, nor third..!), so I'm happy to accept guidance.
